import { readFileSync, writeFileSync } from "node:fs";
import builtins from "builtin-modules";
import esbuild from "esbuild";

const production = process.argv[2] === "production";

/** styles.css is the emulator's own stylesheet plus this plugin's sizing rules. */
function buildStyles() {
  const vendor = readFileSync(
    "node_modules/@wterm/dom/src/terminal.css",
    "utf8",
  );
  const own = readFileSync("src/plugin.css", "utf8");
  writeFileSync(
    "styles.css",
    `/* Generated by esbuild.config.mjs — edit src/plugin.css instead. */\n\n${vendor}\n${own}`,
  );
}

buildStyles();

const context = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  // node-pty ships a platform-specific native addon; it is loaded from the
  // plugin folder's node_modules at runtime rather than bundled.
  external: ["obsidian", "electron", "node-pty", ...builtins],
  format: "cjs",
  platform: "node",
  target: "es2022",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  minify: production,
  outfile: "main.js",
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
